ALTER TABLE "Card"
ADD COLUMN "lastFour" TEXT NOT NULL DEFAULT '0000',
ADD COLUMN "expires" TEXT NOT NULL DEFAULT '00/00',
ADD COLUMN "network" TEXT NOT NULL DEFAULT 'Unknown',
ADD COLUMN "colors" TEXT NOT NULL DEFAULT '#000000';

ALTER TABLE "Card"
ALTER COLUMN "lastFour" DROP DEFAULT,
ALTER COLUMN "expires" DROP DEFAULT,
ALTER COLUMN "network" DROP DEFAULT,
ALTER COLUMN "colors" DROP DEFAULT;
